### ISSUE TITLE
으악

### ISSUE THREAD

**Issue by HotoRas** [HotoRas/blog#1]
https://github.com/HotoRas/blog/actions/runs/12217810753/job/34082537744

@jyhyun1008 얘 좀 해독해주세오 ㅜ

**Comment by HotoRas** [comment]
```log
error
at ./.nuxt/prerender/chunks/build/index-4GzVUQy4.mjs:78:232 (`/`.mjsUnwrap)
at ssrRenderList
at ./.nuxt/Prerender/chunks/build/index-4GzVUQy4.mjs:75:7
    (`/`.mjsUnwrap().return(...,template))
                                ^^^^^^^^
```
네?

**Comment by HotoRas** [comment]
터진 이유: 본문과의 구분을
```md
==============================
title
==============================

body
```
가 아니라
```md
title
<--->
body
```
로 하는데
```md
title
<---->
    ^
body
```
이렇게 입력해서 터진 거였음

md파일 수정해서 일단 해결봤고요
지운 README 복구하고 파싱에러 고친 커밋 끌어오는 건 지금은 힘들고 나중에 체리픽으로 긁어오겠음
- resolves with 3aa30ec6a88cf679e4b1305a33c1db15a6d6b529
